// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: taxonomyservice.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IWA.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from taxonomyservice.proto</summary>
  public static partial class TaxonomyserviceReflection {

    #region Descriptor
    /// <summary>File descriptor for taxonomyservice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TaxonomyserviceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV0YXhvbm9teXNlcnZpY2UucHJvdG8SEHRheG9ub215LnNlcnZpY2UaDnRh",
            "eG9ub215LnByb3RvGgpjb3JlLnByb3RvGg5hcnRpZmFjdC5wcm90byIWChRD",
            "b25maWd1cmF0aW9uUmVxdWVzdDLcCgoPVGF4b25vbXlTZXJ2aWNlEk4KD0dl",
            "dEZ1bGxUYXhvbm9teRIfLnRheG9ub215Lm1vZGVsLlRheG9ub215VmVyc2lv",
            "bhoYLnRheG9ub215Lm1vZGVsLlRheG9ub215IgASVwoPR2V0QmFzZUFydGlm",
            "YWN0EicudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQXJ0aWZhY3RTeW1ib2wa",
            "GS50YXhvbm9teS5tb2RlbC5jb3JlLkJhc2UiABJfChNHZXRCZWhhdmlvckFy",
            "dGlmYWN0EicudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQXJ0aWZhY3RTeW1i",
            "b2waHS50YXhvbm9teS5tb2RlbC5jb3JlLkJlaGF2aW9yIgASaQoYR2V0QmVo",
            "YXZpb3JHcm91cEFydGlmYWN0EicudGF4b25vbXkubW9kZWwuYXJ0aWZhY3Qu",
            "QXJ0aWZhY3RTeW1ib2waIi50YXhvbm9teS5tb2RlbC5jb3JlLkJlaGF2aW9y",
            "R3JvdXAiABJlChZHZXRQcm9wZXJ0eVNldEFydGlmYWN0EicudGF4b25vbXku",
            "bW9kZWwuYXJ0aWZhY3QuQXJ0aWZhY3RTeW1ib2waIC50YXhvbm9teS5tb2Rl",
            "bC5jb3JlLlByb3BlcnR5U2V0IgASagoYR2V0VG9rZW5UZW1wbGF0ZUFydGlm",
            "YWN0EigudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuVGF4b25vbXlGb3JtdWxh",
            "GiIudGF4b25vbXkubW9kZWwuY29yZS5Ub2tlblRlbXBsYXRlIgASYwoSR2V0",
            "QXJ0aWZhY3RzT2ZUeXBlEiUudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuUXVl",
            "cnlPcHRpb25zGiQudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuUXVlcnlSZXN1",
            "bHQiABJtCg5DcmVhdGVBcnRpZmFjdBIrLnRheG9ub215Lm1vZGVsLmFydGlm",
            "YWN0Lk5ld0FydGlmYWN0UmVxdWVzdBosLnRheG9ub215Lm1vZGVsLmFydGlm",
            "YWN0Lk5ld0FydGlmYWN0UmVzcG9uc2UiABJzCg5VcGRhdGVBcnRpZmFjdBIu",
            "LnRheG9ub215Lm1vZGVsLmFydGlmYWN0LlVwZGF0ZUFydGlmYWN0UmVxdWVz",
            "dBovLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LlVwZGF0ZUFydGlmYWN0UmVz",
            "cG9uc2UiABJzCg5EZWxldGVBcnRpZmFjdBIuLnRheG9ub215Lm1vZGVsLmFy",
            "dGlmYWN0LkRlbGV0ZUFydGlmYWN0UmVxdWVzdBovLnRheG9ub215Lm1vZGVs",
            "LmFydGlmYWN0LkRlbGV0ZUFydGlmYWN0UmVzcG9uc2UiABJ1ChJDb21taXRM",
            "b2NhbFVwZGF0ZXMSLS50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5Db21taXRV",
            "cGRhdGVzUmVxdWVzdBouLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LkNvbW1p",
            "dFVwZGF0ZXNSZXNwb25zZSIAEmYKC1B1bGxSZXF1ZXN0EikudGF4b25vbXku",
            "bW9kZWwuYXJ0aWZhY3QuSXNzdWVQdWxsUmVxdWVzdBoqLnRheG9ub215Lm1v",
            "ZGVsLmFydGlmYWN0Lklzc3VlUHVsbFJlc3BvbnNlIgASZAoJR2V0Q29uZmln",
            "EiYudGF4b25vbXkuc2VydmljZS5Db25maWd1cmF0aW9uUmVxdWVzdBotLnRh",
            "eG9ub215Lm1vZGVsLmFydGlmYWN0LlNlcnZpY2VDb25maWd1cmF0aW9uIgBC",
            "KwoUb3JnLnR0aS50dGYudGF4b25vbXlQAaoCEFRUSS5UVEYuVGF4b25vbXli",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IWA.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::IWA.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::IWA.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::IWA.TTF.Taxonomy.ConfigurationRequest), global::IWA.TTF.Taxonomy.ConfigurationRequest.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigurationRequest : pb::IMessage<ConfigurationRequest> {
    private static readonly pb::MessageParser<ConfigurationRequest> _parser = new pb::MessageParser<ConfigurationRequest>(() => new ConfigurationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigurationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::IWA.TTF.Taxonomy.TaxonomyserviceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigurationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigurationRequest(ConfigurationRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigurationRequest Clone() {
      return new ConfigurationRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigurationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigurationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigurationRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
