// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IWA.TTF.Taxonomy {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgh0YXhvbm9teRoOdGF4b25vbXkucHJvdG8aCmNv",
            "cmUucHJvdG8aDmFydGlmYWN0LnByb3RvMvcPCgdTZXJ2aWNlEk4KD0dldEZ1",
            "bGxUYXhvbm9teRIfLnRheG9ub215Lm1vZGVsLlRheG9ub215VmVyc2lvbhoY",
            "LnRheG9ub215Lm1vZGVsLlRheG9ub215IgASTgoPR2V0TGl0ZVRheG9ub215",
            "Eh8udGF4b25vbXkubW9kZWwuVGF4b25vbXlWZXJzaW9uGhgudGF4b25vbXku",
            "bW9kZWwuVGF4b25vbXkiABJXCg9HZXRCYXNlQXJ0aWZhY3QSJy50YXhvbm9t",
            "eS5tb2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBoZLnRheG9ub215Lm1v",
            "ZGVsLmNvcmUuQmFzZSIAEl8KE0dldEJlaGF2aW9yQXJ0aWZhY3QSJy50YXhv",
            "bm9teS5tb2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJvbBodLnRheG9ub215",
            "Lm1vZGVsLmNvcmUuQmVoYXZpb3IiABJpChhHZXRCZWhhdmlvckdyb3VwQXJ0",
            "aWZhY3QSJy50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5BcnRpZmFjdFN5bWJv",
            "bBoiLnRheG9ub215Lm1vZGVsLmNvcmUuQmVoYXZpb3JHcm91cCIAEmUKFkdl",
            "dFByb3BlcnR5U2V0QXJ0aWZhY3QSJy50YXhvbm9teS5tb2RlbC5hcnRpZmFj",
            "dC5BcnRpZmFjdFN5bWJvbBogLnRheG9ub215Lm1vZGVsLmNvcmUuUHJvcGVy",
            "dHlTZXQiABJtChpHZXRUZW1wbGF0ZUZvcm11bGFBcnRpZmFjdBInLnRheG9u",
            "b215Lm1vZGVsLmFydGlmYWN0LkFydGlmYWN0U3ltYm9sGiQudGF4b25vbXku",
            "bW9kZWwuY29yZS5UZW1wbGF0ZUZvcm11bGEiABJzCh1HZXRUZW1wbGF0ZURl",
            "ZmluaXRpb25BcnRpZmFjdBInLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LkFy",
            "dGlmYWN0U3ltYm9sGicudGF4b25vbXkubW9kZWwuY29yZS5UZW1wbGF0ZURl",
            "ZmluaXRpb24iABJiChBHZXRUb2tlblRlbXBsYXRlEigudGF4b25vbXkubW9k",
            "ZWwuYXJ0aWZhY3QuVG9rZW5UZW1wbGF0ZUlkGiIudGF4b25vbXkubW9kZWwu",
            "Y29yZS5Ub2tlblRlbXBsYXRlIgASbAoVR2V0VG9rZW5TcGVjaWZpY2F0aW9u",
            "EigudGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuVG9rZW5UZW1wbGF0ZUlkGicu",
            "dGF4b25vbXkubW9kZWwuY29yZS5Ub2tlblNwZWNpZmljYXRpb24iABJjChJH",
            "ZXRBcnRpZmFjdHNPZlR5cGUSJS50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5R",
            "dWVyeU9wdGlvbnMaJC50YXhvbm9teS5tb2RlbC5hcnRpZmFjdC5RdWVyeVJl",
            "c3VsdCIAEogBChVJbml0aWFsaXplTmV3QXJ0aWZhY3QSNS50YXhvbm9teS5t",
            "b2RlbC5hcnRpZmFjdC5Jbml0aWFsaXplTmV3QXJ0aWZhY3RSZXF1ZXN0GjYu",
            "dGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuSW5pdGlhbGl6ZU5ld0FydGlmYWN0",
            "UmVzcG9uc2UiABJtCg5DcmVhdGVBcnRpZmFjdBIrLnRheG9ub215Lm1vZGVs",
            "LmFydGlmYWN0Lk5ld0FydGlmYWN0UmVxdWVzdBosLnRheG9ub215Lm1vZGVs",
            "LmFydGlmYWN0Lk5ld0FydGlmYWN0UmVzcG9uc2UiABJzCg5VcGRhdGVBcnRp",
            "ZmFjdBIuLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LlVwZGF0ZUFydGlmYWN0",
            "UmVxdWVzdBovLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LlVwZGF0ZUFydGlm",
            "YWN0UmVzcG9uc2UiABJzCg5EZWxldGVBcnRpZmFjdBIuLnRheG9ub215Lm1v",
            "ZGVsLmFydGlmYWN0LkRlbGV0ZUFydGlmYWN0UmVxdWVzdBovLnRheG9ub215",
            "Lm1vZGVsLmFydGlmYWN0LkRlbGV0ZUFydGlmYWN0UmVzcG9uc2UiABJ1ChhD",
            "cmVhdGVUZW1wbGF0ZURlZmluaXRpb24SLi50YXhvbm9teS5tb2RlbC5hcnRp",
            "ZmFjdC5OZXdUZW1wbGF0ZURlZmluaXRpb24aJy50YXhvbm9teS5tb2RlbC5j",
            "b3JlLlRlbXBsYXRlRGVmaW5pdGlvbiIAEnUKEkNvbW1pdExvY2FsVXBkYXRl",
            "cxItLnRheG9ub215Lm1vZGVsLmFydGlmYWN0LkNvbW1pdFVwZGF0ZXNSZXF1",
            "ZXN0Gi4udGF4b25vbXkubW9kZWwuYXJ0aWZhY3QuQ29tbWl0VXBkYXRlc1Jl",
            "c3BvbnNlIgASZgoLUHVsbFJlcXVlc3QSKS50YXhvbm9teS5tb2RlbC5hcnRp",
            "ZmFjdC5Jc3N1ZVB1bGxSZXF1ZXN0GioudGF4b25vbXkubW9kZWwuYXJ0aWZh",
            "Y3QuSXNzdWVQdWxsUmVzcG9uc2UiABJrCglHZXRDb25maWcSLS50YXhvbm9t",
            "eS5tb2RlbC5hcnRpZmFjdC5Db25maWd1cmF0aW9uUmVxdWVzdBotLnRheG9u",
            "b215Lm1vZGVsLmFydGlmYWN0LlNlcnZpY2VDb25maWd1cmF0aW9uIgBCKwoU",
            "b3JnLml3YS50dGYudGF4b25vbXlQAaoCEElXQS5UVEYuVGF4b25vbXliBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IWA.TTF.Taxonomy.Model.TaxonomyReflection.Descriptor, global::IWA.TTF.Taxonomy.Model.Core.CoreReflection.Descriptor, global::IWA.TTF.Taxonomy.Model.Artifact.ArtifactReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
