// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: printersvc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace IWA.TTF.Taxonomy {
  /// <summary>
  ///Service to Print Artifacts to OpenXML format.
  /// </summary>
  public static partial class PrinterService
  {
    static readonly string __ServiceName = "taxonomy.ttfprinter.PrinterService";

    static readonly grpc::Marshaller<global::IWA.TTF.Taxonomy.ArtifactToPrint> __Marshaller_taxonomy_ttfprinter_ArtifactToPrint = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IWA.TTF.Taxonomy.ArtifactToPrint.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::IWA.TTF.Taxonomy.PrintResult> __Marshaller_taxonomy_ttfprinter_PrintResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IWA.TTF.Taxonomy.PrintResult.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::IWA.TTF.Taxonomy.PrintTTFOptions> __Marshaller_taxonomy_ttfprinter_PrintTTFOptions = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::IWA.TTF.Taxonomy.PrintTTFOptions.Parser.ParseFrom);

    static readonly grpc::Method<global::IWA.TTF.Taxonomy.ArtifactToPrint, global::IWA.TTF.Taxonomy.PrintResult> __Method_PrintTTFArtifact = new grpc::Method<global::IWA.TTF.Taxonomy.ArtifactToPrint, global::IWA.TTF.Taxonomy.PrintResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PrintTTFArtifact",
        __Marshaller_taxonomy_ttfprinter_ArtifactToPrint,
        __Marshaller_taxonomy_ttfprinter_PrintResult);

    static readonly grpc::Method<global::IWA.TTF.Taxonomy.PrintTTFOptions, global::IWA.TTF.Taxonomy.PrintResult> __Method_PrintTTF = new grpc::Method<global::IWA.TTF.Taxonomy.PrintTTFOptions, global::IWA.TTF.Taxonomy.PrintResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PrintTTF",
        __Marshaller_taxonomy_ttfprinter_PrintTTFOptions,
        __Marshaller_taxonomy_ttfprinter_PrintResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::IWA.TTF.Taxonomy.PrintersvcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PrinterService</summary>
    [grpc::BindServiceMethod(typeof(PrinterService), "BindService")]
    public abstract partial class PrinterServiceBase
    {
      /// <summary>
      ///Print an artifact by Type and Id.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::IWA.TTF.Taxonomy.PrintResult> PrintTTFArtifact(global::IWA.TTF.Taxonomy.ArtifactToPrint request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Print all artifacts in either multiple artifact files in their repective artifact folders or a single TTF Book file.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::IWA.TTF.Taxonomy.PrintResult> PrintTTF(global::IWA.TTF.Taxonomy.PrintTTFOptions request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PrinterService</summary>
    public partial class PrinterServiceClient : grpc::ClientBase<PrinterServiceClient>
    {
      /// <summary>Creates a new client for PrinterService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PrinterServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PrinterService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PrinterServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PrinterServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PrinterServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Print an artifact by Type and Id.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::IWA.TTF.Taxonomy.PrintResult PrintTTFArtifact(global::IWA.TTF.Taxonomy.ArtifactToPrint request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PrintTTFArtifact(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Print an artifact by Type and Id.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::IWA.TTF.Taxonomy.PrintResult PrintTTFArtifact(global::IWA.TTF.Taxonomy.ArtifactToPrint request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PrintTTFArtifact, null, options, request);
      }
      /// <summary>
      ///Print an artifact by Type and Id.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::IWA.TTF.Taxonomy.PrintResult> PrintTTFArtifactAsync(global::IWA.TTF.Taxonomy.ArtifactToPrint request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PrintTTFArtifactAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Print an artifact by Type and Id.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::IWA.TTF.Taxonomy.PrintResult> PrintTTFArtifactAsync(global::IWA.TTF.Taxonomy.ArtifactToPrint request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PrintTTFArtifact, null, options, request);
      }
      /// <summary>
      ///Print all artifacts in either multiple artifact files in their repective artifact folders or a single TTF Book file.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::IWA.TTF.Taxonomy.PrintResult PrintTTF(global::IWA.TTF.Taxonomy.PrintTTFOptions request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PrintTTF(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Print all artifacts in either multiple artifact files in their repective artifact folders or a single TTF Book file.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::IWA.TTF.Taxonomy.PrintResult PrintTTF(global::IWA.TTF.Taxonomy.PrintTTFOptions request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PrintTTF, null, options, request);
      }
      /// <summary>
      ///Print all artifacts in either multiple artifact files in their repective artifact folders or a single TTF Book file.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::IWA.TTF.Taxonomy.PrintResult> PrintTTFAsync(global::IWA.TTF.Taxonomy.PrintTTFOptions request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PrintTTFAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Print all artifacts in either multiple artifact files in their repective artifact folders or a single TTF Book file.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::IWA.TTF.Taxonomy.PrintResult> PrintTTFAsync(global::IWA.TTF.Taxonomy.PrintTTFOptions request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PrintTTF, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PrinterServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PrinterServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PrinterServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PrintTTFArtifact, serviceImpl.PrintTTFArtifact)
          .AddMethod(__Method_PrintTTF, serviceImpl.PrintTTF).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PrinterServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PrintTTFArtifact, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::IWA.TTF.Taxonomy.ArtifactToPrint, global::IWA.TTF.Taxonomy.PrintResult>(serviceImpl.PrintTTFArtifact));
      serviceBinder.AddMethod(__Method_PrintTTF, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::IWA.TTF.Taxonomy.PrintTTFOptions, global::IWA.TTF.Taxonomy.PrintResult>(serviceImpl.PrintTTF));
    }

  }
}
#endregion
